"""
Demo seed data for PRAKRITI.
Fictional data inspired by a multi-hazard Indian district disaster scenario.
All villages, names, and statistics are FICTIONAL and for demonstration purposes only.
"""

from datetime import datetime, timedelta, timezone

# ─── Fictional district info ───
DISTRICT = "Aranyapur District (DEMO)"
STATE = "Himachal Pradesh (fictional)"

# ─── Timestamp helpers ───
def t(hours_ago: float) -> str:
    return (datetime.now(timezone.utc) - timedelta(hours=hours_ago)).isoformat()


DEMO_VILLAGES = [
    {
        "name": "Kalivadi",
        "block": "Nandipura Block",
        "lat": 23.2150, "lng": 85.3340,
        "disaster_types": ["flood", "road_failure"],
        "severity": "critical",
        "severity_score": 92.0,
        "total_population": 1240,
        "affected_population": 980,
        "stranded_population": 620,
        "vulnerable_population": 190,
        "medical_emergencies": 6,
        "rescue_priority_score": 94.0,
        "priority_class": "P1",
        "confidence_score": 91.0,
        "information_fog_score": 18.0,
        "accessibility_score": 14.0,
        "is_accessible": False,
        "communication_active": True,
        "communication_gap_hours": 0,
        "distance_from_center_km": 22.0,
        "report_count": 11,
        "verified_report_count": 3,
        "contradiction_count": 2,
        "assigned_resources": [],
        "priority_reasons": [
            "Critical flooding – 72% area submerged",
            "980 people at risk",
            "Main road R-03 blocked by debris",
            "6 medical emergency reports",
            "Evidence confidence 91% (official + satellite + citizen reports)",
            "No rescue resource currently assigned"
        ],
        "evidence_breakdown": {
            "satellite": 92.0, "official": 80.0, "citizen": 55.0
        },
        "timeline": [
            {"time": t(8.5), "event": "First citizen report received", "type": "report"},
            {"time": t(8.0), "event": "Police report confirmed flooding", "type": "report"},
            {"time": t(7.1), "event": "Satellite evidence received – severe flooding confirmed", "type": "satellite"},
            {"time": t(6.8), "event": "Contradiction detected in reports (severity)", "type": "contradiction"},
            {"time": t(6.0), "event": "AI damage assessment completed", "type": "ai"},
            {"time": t(5.5), "event": "Classified CRITICAL", "type": "alert"},
            {"time": t(5.0), "event": "Rescue boat B-01 recommended", "type": "resource"},
        ],
    },
    {
        "name": "Rajpur Tola",
        "block": "Nandipura Block",
        "lat": 23.2280, "lng": 85.3510,
        "disaster_types": ["building_collapse", "flood"],
        "severity": "critical",
        "severity_score": 88.0,
        "total_population": 870,
        "affected_population": 760,
        "stranded_population": 410,
        "vulnerable_population": 145,
        "medical_emergencies": 4,
        "rescue_priority_score": 87.0,
        "priority_class": "P1",
        "confidence_score": 85.0,
        "information_fog_score": 22.0,
        "accessibility_score": 20.0,
        "is_accessible": False,
        "communication_active": True,
        "communication_gap_hours": 0,
        "distance_from_center_km": 18.5,
        "report_count": 8,
        "verified_report_count": 2,
        "contradiction_count": 1,
        "assigned_resources": ["AMB-01"],
        "priority_reasons": [
            "Building collapse reported in 3 structures",
            "760 people at risk",
            "Partial road access only",
            "4 medical emergency reports",
            "Ambulance AMB-01 deployed"
        ],
        "evidence_breakdown": {"official": 88.0, "citizen": 50.0},
        "timeline": [
            {"time": t(7.2), "event": "Building collapse reported – Rajpur Main Street", "type": "report"},
            {"time": t(6.9), "event": "Official confirmation received", "type": "report"},
            {"time": t(6.0), "event": "AI damage assessment – 3 structures collapsed", "type": "ai"},
            {"time": t(5.5), "event": "Classified CRITICAL", "type": "alert"},
            {"time": t(5.0), "event": "AMB-01 dispatched", "type": "resource"},
        ],
    },
    {
        "name": "Baiganbari",
        "block": "Kumarhat Block",
        "lat": 23.1980, "lng": 85.3700,
        "disaster_types": ["landslide", "road_failure", "flood"],
        "severity": "critical",
        "severity_score": 86.0,
        "total_population": 540,
        "affected_population": 490,
        "stranded_population": 490,
        "vulnerable_population": 110,
        "medical_emergencies": 3,
        "rescue_priority_score": 82.0,
        "priority_class": "P1",
        "confidence_score": 79.0,
        "information_fog_score": 38.0,
        "accessibility_score": 8.0,
        "is_accessible": False,
        "communication_active": False,
        "communication_gap_hours": 5.5,
        "distance_from_center_km": 34.0,
        "report_count": 5,
        "verified_report_count": 1,
        "contradiction_count": 0,
        "assigned_resources": [],
        "priority_reasons": [
            "Landslide has completely cut off all road access",
            "490 people stranded with NO exit route",
            "Communication partially lost (5.5 hour gap)",
            "3 medical emergencies reported before comms loss",
            "Most remote village in affected zone"
        ],
        "evidence_breakdown": {"satellite": 79.0, "citizen": 40.0},
        "timeline": [
            {"time": t(9.0), "event": "Last citizen report received", "type": "report"},
            {"time": t(8.5), "event": "Landslide reported on R-07 approach road", "type": "report"},
            {"time": t(7.0), "event": "Satellite confirms landslide debris", "type": "satellite"},
            {"time": t(5.5), "event": "⚠️ Communication gap detected – 5.5 hrs", "type": "alert"},
            {"time": t(5.0), "event": "Classified CRITICAL – information blackout", "type": "alert"},
        ],
    },
    {
        "name": "Sundarnagar Village",
        "block": "Kumarhat Block",
        "lat": 23.2080, "lng": 85.3870,
        "disaster_types": ["flood"],
        "severity": "high",
        "severity_score": 72.0,
        "total_population": 1580,
        "affected_population": 890,
        "stranded_population": 320,
        "vulnerable_population": 210,
        "medical_emergencies": 2,
        "rescue_priority_score": 73.0,
        "priority_class": "P2",
        "confidence_score": 88.0,
        "information_fog_score": 19.0,
        "accessibility_score": 42.0,
        "is_accessible": True,
        "communication_active": True,
        "communication_gap_hours": 0,
        "distance_from_center_km": 14.0,
        "report_count": 9,
        "verified_report_count": 4,
        "contradiction_count": 1,
        "assigned_resources": ["BOAT-02"],
        "priority_reasons": [
            "Major flooding – 60% residential area submerged",
            "890 people affected",
            "2 medical emergencies",
            "BOAT-02 dispatched"
        ],
        "evidence_breakdown": {"official": 88.0, "police": 80.0, "citizen": 55.0},
        "timeline": [
            {"time": t(6.5), "event": "Multiple citizen reports – severe flooding", "type": "report"},
            {"time": t(5.8), "event": "Official report confirmed", "type": "report"},
            {"time": t(5.0), "event": "Classified HIGH priority", "type": "alert"},
            {"time": t(4.5), "event": "BOAT-02 dispatched", "type": "resource"},
        ],
    },
    {
        "name": "Dhanipur",
        "block": "Nandipura Block",
        "lat": 23.2350, "lng": 85.3200,
        "disaster_types": ["flood", "landslide"],
        "severity": "high",
        "severity_score": 68.0,
        "total_population": 720,
        "affected_population": 510,
        "stranded_population": 180,
        "vulnerable_population": 95,
        "medical_emergencies": 1,
        "rescue_priority_score": 65.0,
        "priority_class": "P2",
        "confidence_score": 74.0,
        "information_fog_score": 44.0,
        "accessibility_score": 35.0,
        "is_accessible": True,
        "communication_active": True,
        "communication_gap_hours": 2.0,
        "distance_from_center_km": 16.0,
        "report_count": 6,
        "verified_report_count": 1,
        "contradiction_count": 1,
        "assigned_resources": [],
        "priority_reasons": [
            "Combined flood and landslide risk",
            "510 people affected",
            "High information fog – conflicting reports",
            "No rescue resource assigned"
        ],
        "evidence_breakdown": {"citizen": 55.0, "police": 80.0},
        "timeline": [
            {"time": t(7.0), "event": "Citizen reports flooding", "type": "report"},
            {"time": t(6.5), "event": "Contradiction detected: reports disagree on severity", "type": "contradiction"},
            {"time": t(5.5), "event": "Classified HIGH priority", "type": "alert"},
        ],
    },
    {
        "name": "Mahuatoli",
        "block": "Shivpur Block",
        "lat": 23.1850, "lng": 85.3480,
        "disaster_types": ["flood"],
        "severity": "high",
        "severity_score": 65.0,
        "total_population": 430,
        "affected_population": 310,
        "stranded_population": 150,
        "vulnerable_population": 75,
        "medical_emergencies": 2,
        "rescue_priority_score": 60.0,
        "priority_class": "P2",
        "confidence_score": 70.0,
        "information_fog_score": 50.0,
        "accessibility_score": 48.0,
        "is_accessible": True,
        "communication_active": True,
        "communication_gap_hours": 0,
        "distance_from_center_km": 12.0,
        "report_count": 4,
        "verified_report_count": 1,
        "contradiction_count": 0,
        "assigned_resources": [],
        "priority_reasons": [
            "Significant flooding",
            "310 people affected",
            "2 medical emergencies",
            "Moderate information fog"
        ],
        "evidence_breakdown": {"citizen": 55.0, "official": 70.0},
        "timeline": [
            {"time": t(5.0), "event": "Flooding reported by residents", "type": "report"},
            {"time": t(4.5), "event": "Official assessment team dispatched", "type": "report"},
            {"time": t(3.5), "event": "Classified HIGH priority", "type": "alert"},
        ],
    },
    {
        "name": "Koilpur",
        "block": "Kumarhat Block",
        "lat": 23.2180, "lng": 85.4020,
        "disaster_types": ["building_collapse"],
        "severity": "moderate",
        "severity_score": 52.0,
        "total_population": 310,
        "affected_population": 180,
        "stranded_population": 60,
        "vulnerable_population": 45,
        "medical_emergencies": 1,
        "rescue_priority_score": 48.0,
        "priority_class": "P3",
        "confidence_score": 65.0,
        "information_fog_score": 55.0,
        "accessibility_score": 65.0,
        "is_accessible": True,
        "communication_active": True,
        "communication_gap_hours": 0,
        "distance_from_center_km": 9.0,
        "report_count": 3,
        "verified_report_count": 1,
        "contradiction_count": 0,
        "assigned_resources": [],
        "priority_reasons": [
            "Partial building collapse reported",
            "180 people affected",
            "Limited verification available"
        ],
        "evidence_breakdown": {"citizen": 55.0, "official": 65.0},
        "timeline": [
            {"time": t(4.0), "event": "Building collapse report", "type": "report"},
            {"time": t(3.5), "event": "Classified MODERATE", "type": "alert"},
        ],
    },
    {
        "name": "Banshipur",
        "block": "Shivpur Block",
        "lat": 23.1720, "lng": 85.3650,
        "disaster_types": ["flood", "road_failure"],
        "severity": "moderate",
        "severity_score": 48.0,
        "total_population": 890,
        "affected_population": 340,
        "stranded_population": 90,
        "vulnerable_population": 88,
        "medical_emergencies": 0,
        "rescue_priority_score": 42.0,
        "priority_class": "P3",
        "confidence_score": 60.0,
        "information_fog_score": 61.0,
        "accessibility_score": 55.0,
        "is_accessible": True,
        "communication_active": True,
        "communication_gap_hours": 1.0,
        "distance_from_center_km": 10.0,
        "report_count": 3,
        "verified_report_count": 0,
        "contradiction_count": 1,
        "assigned_resources": [],
        "priority_reasons": [
            "Moderate flooding and road damage",
            "340 people affected",
            "No official verification yet",
            "Contradictory reports pending resolution"
        ],
        "evidence_breakdown": {"citizen": 40.0, "social_media": 25.0},
        "timeline": [
            {"time": t(3.5), "event": "Social media reports of flooding", "type": "report"},
            {"time": t(3.0), "event": "Contradiction in severity reports", "type": "contradiction"},
            {"time": t(2.5), "event": "Classified MODERATE", "type": "alert"},
        ],
    },
    {
        "name": "Rampur Khurd",
        "block": "Nandipura Block",
        "lat": 23.2440, "lng": 85.3420,
        "disaster_types": ["flood"],
        "severity": "moderate",
        "severity_score": 44.0,
        "total_population": 560,
        "affected_population": 210,
        "stranded_population": 50,
        "vulnerable_population": 62,
        "medical_emergencies": 0,
        "rescue_priority_score": 38.0,
        "priority_class": "P3",
        "confidence_score": 55.0,
        "information_fog_score": 65.0,
        "accessibility_score": 72.0,
        "is_accessible": True,
        "communication_active": True,
        "communication_gap_hours": 0,
        "distance_from_center_km": 8.0,
        "report_count": 2,
        "verified_report_count": 0,
        "contradiction_count": 0,
        "assigned_resources": [],
        "priority_reasons": [
            "Moderate flooding reported",
            "210 people affected",
            "Insufficient verification"
        ],
        "evidence_breakdown": {"citizen": 45.0},
        "timeline": [
            {"time": t(2.5), "event": "Flooding reported by 2 citizens", "type": "report"},
            {"time": t(2.0), "event": "Classified MODERATE – pending verification", "type": "alert"},
        ],
    },
    {
        "name": "Tulsibari",
        "block": "Shivpur Block",
        "lat": 23.1650, "lng": 85.3520,
        "disaster_types": [],
        "severity": "low",
        "severity_score": 15.0,
        "total_population": 330,
        "affected_population": 30,
        "stranded_population": 0,
        "vulnerable_population": 18,
        "medical_emergencies": 0,
        "rescue_priority_score": 12.0,
        "priority_class": "P4",
        "confidence_score": 40.0,
        "information_fog_score": 74.0,
        "accessibility_score": 85.0,
        "is_accessible": True,
        "communication_active": False,
        "communication_gap_hours": 9.0,
        "distance_from_center_km": 6.0,
        "report_count": 0,
        "verified_report_count": 0,
        "contradiction_count": 0,
        "assigned_resources": [],
        "priority_reasons": [
            "⚠️ COMMUNICATION BLACKOUT – 9 hours no contact",
            "No reports received – absence does not confirm safety",
            "Satellite verification recommended"
        ],
        "evidence_breakdown": {},
        "timeline": [
            {"time": t(9.0), "event": "Last known contact with village", "type": "report"},
            {"time": t(5.0), "event": "⚠️ Communication gap flagged – 4 hours", "type": "alert"},
            {"time": t(1.0), "event": "🚨 INFORMATION BLACKOUT – 9 hours silence", "type": "alert"},
        ],
    },
    {
        "name": "Gopaltola",
        "block": "Kumarhat Block",
        "lat": 23.2060, "lng": 85.4150,
        "disaster_types": ["cyclone", "flood"],
        "severity": "high",
        "severity_score": 70.0,
        "total_population": 680,
        "affected_population": 480,
        "stranded_population": 200,
        "vulnerable_population": 98,
        "medical_emergencies": 3,
        "rescue_priority_score": 68.0,
        "priority_class": "P2",
        "confidence_score": 76.0,
        "information_fog_score": 35.0,
        "accessibility_score": 38.0,
        "is_accessible": True,
        "communication_active": True,
        "communication_gap_hours": 0.5,
        "distance_from_center_km": 20.0,
        "report_count": 6,
        "verified_report_count": 2,
        "contradiction_count": 0,
        "assigned_resources": [],
        "priority_reasons": [
            "Cyclone + flood combined hazard",
            "480 people affected",
            "3 medical emergencies",
            "Road R-09 partially flooded"
        ],
        "evidence_breakdown": {"official": 88.0, "citizen": 55.0},
        "timeline": [
            {"time": t(6.0), "event": "Cyclone damage reported", "type": "report"},
            {"time": t(5.5), "event": "Flooding secondary impact confirmed", "type": "report"},
            {"time": t(5.0), "event": "Classified HIGH priority", "type": "alert"},
        ],
    },
    {
        "name": "Harinagar",
        "block": "Shivpur Block",
        "lat": 23.1780, "lng": 85.3810,
        "disaster_types": ["flood"],
        "severity": "low",
        "severity_score": 22.0,
        "total_population": 445,
        "affected_population": 55,
        "stranded_population": 10,
        "vulnerable_population": 25,
        "medical_emergencies": 0,
        "rescue_priority_score": 18.0,
        "priority_class": "P4",
        "confidence_score": 52.0,
        "information_fog_score": 68.0,
        "accessibility_score": 88.0,
        "is_accessible": True,
        "communication_active": True,
        "communication_gap_hours": 0,
        "distance_from_center_km": 5.0,
        "report_count": 2,
        "verified_report_count": 0,
        "contradiction_count": 0,
        "assigned_resources": [],
        "priority_reasons": ["Minor flooding – monitoring", "55 people affected"],
        "evidence_breakdown": {"citizen": 40.0},
        "timeline": [
            {"time": t(2.0), "event": "Minor flooding reported", "type": "report"},
            {"time": t(1.5), "event": "Classified LOW priority – monitoring", "type": "alert"},
        ],
    },
    {
        "name": "Madhupur",
        "block": "Nandipura Block",
        "lat": 23.2510, "lng": 85.3640,
        "disaster_types": ["earthquake", "building_collapse"],
        "severity": "critical",
        "severity_score": 90.0,
        "total_population": 760,
        "affected_population": 650,
        "stranded_population": 300,
        "vulnerable_population": 145,
        "medical_emergencies": 7,
        "rescue_priority_score": 89.0,
        "priority_class": "P1",
        "confidence_score": 83.0,
        "information_fog_score": 28.0,
        "accessibility_score": 25.0,
        "is_accessible": False,
        "communication_active": True,
        "communication_gap_hours": 0,
        "distance_from_center_km": 25.0,
        "report_count": 9,
        "verified_report_count": 3,
        "contradiction_count": 0,
        "assigned_resources": ["EXCAV-01"],
        "priority_reasons": [
            "Earthquake epicentre nearby – major collapse",
            "650 people affected",
            "7 medical emergencies",
            "Primary access road collapsed",
            "EXCAV-01 dispatched for debris clearing"
        ],
        "evidence_breakdown": {"satellite": 83.0, "official": 88.0, "citizen": 55.0},
        "timeline": [
            {"time": t(10.0), "event": "Earthquake M4.8 – tremors reported", "type": "report"},
            {"time": t(9.5), "event": "Building collapse reports flood in", "type": "report"},
            {"time": t(8.5), "event": "Satellite confirms structural collapse", "type": "satellite"},
            {"time": t(7.0), "event": "Classified CRITICAL", "type": "alert"},
            {"time": t(6.5), "event": "EXCAV-01 dispatched", "type": "resource"},
        ],
    },
    {
        "name": "Pratappur",
        "block": "Kumarhat Block",
        "lat": 23.2250, "lng": 85.4290,
        "disaster_types": ["flood", "road_failure"],
        "severity": "moderate",
        "severity_score": 50.0,
        "total_population": 380,
        "affected_population": 220,
        "stranded_population": 80,
        "vulnerable_population": 55,
        "medical_emergencies": 1,
        "rescue_priority_score": 44.0,
        "priority_class": "P3",
        "confidence_score": 62.0,
        "information_fog_score": 57.0,
        "accessibility_score": 58.0,
        "is_accessible": True,
        "communication_active": True,
        "communication_gap_hours": 0,
        "distance_from_center_km": 11.0,
        "report_count": 3,
        "verified_report_count": 1,
        "contradiction_count": 0,
        "assigned_resources": [],
        "priority_reasons": ["Moderate flooding", "220 affected", "Road partially blocked"],
        "evidence_breakdown": {"citizen": 50.0, "police": 75.0},
        "timeline": [
            {"time": t(3.0), "event": "Flooding and road damage reported", "type": "report"},
            {"time": t(2.5), "event": "Classified MODERATE", "type": "alert"},
        ],
    },
]


DEMO_REPORTS = [
    # Kalivadi reports
    {
        "village_name": "Kalivadi", "source_type": "citizen",
        "disaster_type": "flood", "urgency": "critical",
        "description": "Village is completely submerged. Cannot see any roads. People stuck on rooftops screaming for help. Need boats urgently.",
        "affected_count": 400, "reporter_name": "Ramesh Kumar",
        "is_verified": False, "reliability_score": 55.0, "duplicate_probability": 5.0,
        "contradiction_flag": True,
        "contradiction_detail": {"conflict": "another report claims only minor waterlogging"},
        "timestamp": t(8.5),
    },
    {
        "village_name": "Kalivadi", "source_type": "citizen",
        "disaster_type": "flood", "urgency": "critical",
        "description": "Only minor waterlogging in low-lying areas. Most people safe. Situation improving.",
        "affected_count": 50, "reporter_name": "Anonymous",
        "is_verified": False, "reliability_score": 35.0, "duplicate_probability": 8.0,
        "contradiction_flag": True,
        "contradiction_detail": {"conflict": "contradicts severe flooding reports"},
        "timestamp": t(8.2),
    },
    {
        "village_name": "Kalivadi", "source_type": "official",
        "disaster_type": "flood", "urgency": "critical",
        "description": "BDO confirms severe flooding. Main road washed out. Satellite images show 72% area underwater. Medical team required urgently.",
        "affected_count": 980, "reporter_name": "BDO Nandipura",
        "is_verified": True, "reliability_score": 90.0, "duplicate_probability": 0.0,
        "timestamp": t(7.5),
    },
    {
        "village_name": "Kalivadi", "source_type": "satellite",
        "disaster_type": "flood", "urgency": "critical",
        "description": "Satellite analysis confirms severe inundation. Estimated 72% residential area submerged. 3 structures appear collapsed.",
        "affected_count": 980, "reporter_name": "ISRO Satellite Feed",
        "is_verified": True, "reliability_score": 94.0, "duplicate_probability": 0.0,
        "timestamp": t(7.1),
    },
    {
        "village_name": "Kalivadi", "source_type": "police",
        "disaster_type": "flood", "urgency": "critical",
        "description": "Police patrol confirms road R-03 completely blocked. No vehicle access. Helicopter assessment required.",
        "affected_count": 600, "reporter_name": "Police Station Nandipura",
        "is_verified": True, "reliability_score": 82.0, "duplicate_probability": 0.0,
        "timestamp": t(8.0),
    },
    # Rajpur Tola reports
    {
        "village_name": "Rajpur Tola", "source_type": "citizen",
        "disaster_type": "building_collapse", "urgency": "critical",
        "description": "3 buildings have totally collapsed on main street. People trapped under rubble. Heard screaming. Need excavators.",
        "affected_count": 120, "reporter_name": "Priya Singh",
        "is_verified": False, "reliability_score": 60.0, "duplicate_probability": 3.0,
        "timestamp": t(7.2),
    },
    {
        "village_name": "Rajpur Tola", "source_type": "official",
        "disaster_type": "building_collapse", "urgency": "critical",
        "description": "District engineer confirms partial collapse of 3 structures. 15 persons unaccounted. Structural risk to adjacent buildings.",
        "affected_count": 200, "reporter_name": "District Engineer",
        "is_verified": True, "reliability_score": 88.0, "duplicate_probability": 0.0,
        "timestamp": t(6.9),
    },
    # Baiganbari reports
    {
        "village_name": "Baiganbari", "source_type": "citizen",
        "disaster_type": "landslide", "urgency": "critical",
        "description": "Massive landslide has blocked the only road. Nobody can leave or enter the village. 3 people injured. Phone signal very weak.",
        "affected_count": 490, "reporter_name": "Unknown Caller",
        "is_verified": False, "reliability_score": 50.0, "duplicate_probability": 2.0,
        "timestamp": t(9.0),
    },
    {
        "village_name": "Baiganbari", "source_type": "satellite",
        "disaster_type": "landslide", "urgency": "critical",
        "description": "Satellite confirms large landslide debris blocking R-07. Village appears isolated. No visible human movement on main road.",
        "affected_count": 490, "reporter_name": "Satellite Analysis",
        "is_verified": True, "reliability_score": 92.0, "duplicate_probability": 0.0,
        "timestamp": t(7.0),
    },
    # Sundarnagar reports
    {
        "village_name": "Sundarnagar Village", "source_type": "citizen",
        "disaster_type": "flood", "urgency": "high",
        "description": "Flood water entering homes. Market area submerged. Elderly residents need evacuation. Situation serious.",
        "affected_count": 300, "reporter_name": "Suresh Mehta",
        "is_verified": False, "reliability_score": 55.0, "duplicate_probability": 10.0,
        "timestamp": t(6.5),
    },
    {
        "village_name": "Sundarnagar Village", "source_type": "official",
        "disaster_type": "flood", "urgency": "high",
        "description": "SDM assessment: moderate to severe flooding. Evacuation of lower ward recommended. Road R-12 passable via detour.",
        "affected_count": 890, "reporter_name": "SDM Kumarhat",
        "is_verified": True, "reliability_score": 88.0, "duplicate_probability": 0.0,
        "timestamp": t(5.8),
    },
    # Tulsibari – no reports (communication blackout)
    # Madhupur reports
    {
        "village_name": "Madhupur", "source_type": "citizen",
        "disaster_type": "earthquake", "urgency": "critical",
        "description": "Strong earthquake. Multiple buildings collapsed. Many people trapped. Blood everywhere. Hospitals overwhelmed. SEND HELP.",
        "affected_count": 300, "reporter_name": "Pankaj Yadav",
        "is_verified": False, "reliability_score": 60.0, "duplicate_probability": 5.0,
        "timestamp": t(9.5),
    },
    {
        "village_name": "Madhupur", "source_type": "satellite",
        "disaster_type": "earthquake", "urgency": "critical",
        "description": "Post-event satellite analysis confirms significant structural damage. 8-12 buildings collapsed. Dust signature consistent with seismic event.",
        "affected_count": 650, "reporter_name": "Satellite Analysis",
        "is_verified": True, "reliability_score": 92.0, "duplicate_probability": 0.0,
        "timestamp": t(8.5),
    },
    # Social media duplicate reports
    {
        "village_name": "Sundarnagar Village", "source_type": "social_media",
        "disaster_type": "flood", "urgency": "high",
        "description": "Flood in Sundarnagar! Share and help! #DisasterAlert #Flood",
        "affected_count": 50, "reporter_name": "@user_flood_alert",
        "is_verified": False, "reliability_score": 25.0, "duplicate_probability": 85.0,
        "is_duplicate": True,
        "timestamp": t(5.2),
    },
    {
        "village_name": "Sundarnagar Village", "source_type": "social_media",
        "disaster_type": "flood", "urgency": "high",
        "description": "BREAKING: Flood in Sundarnagar! Share and help! #DisasterAlert",
        "affected_count": 50, "reporter_name": "@newsfeed_hindi",
        "is_verified": False, "reliability_score": 20.0, "duplicate_probability": 90.0,
        "is_duplicate": True,
        "timestamp": t(5.0),
    },
    # Banshipur contradiction
    {
        "village_name": "Banshipur", "source_type": "citizen",
        "disaster_type": "flood", "urgency": "moderate",
        "description": "Banshipur road open – I drove through this morning. Situation normal near market.",
        "affected_count": 0, "reporter_name": "Truck driver",
        "is_verified": False, "reliability_score": 45.0, "duplicate_probability": 0.0,
        "contradiction_flag": True,
        "timestamp": t(3.5),
    },
    {
        "village_name": "Banshipur", "source_type": "police",
        "disaster_type": "road_failure", "urgency": "high",
        "description": "Road critically blocked near bridge B-04. No vehicles passing. Diversion required. Multiple trees fallen.",
        "affected_count": 200, "reporter_name": "Police Patrol Shivpur",
        "is_verified": False, "reliability_score": 75.0, "duplicate_probability": 0.0,
        "contradiction_flag": True,
        "timestamp": t(3.0),
    },
    # Dhanipur contradiction
    {
        "village_name": "Dhanipur", "source_type": "citizen",
        "disaster_type": "flood", "urgency": "high",
        "description": "Dhanipur completely cut off. Road R-05 washed out. Need immediate rescue.",
        "affected_count": 300, "reporter_name": "Local resident",
        "is_verified": False, "reliability_score": 50.0, "duplicate_probability": 0.0,
        "contradiction_flag": True,
        "timestamp": t(7.0),
    },
    {
        "village_name": "Dhanipur", "source_type": "citizen",
        "disaster_type": "flood", "urgency": "moderate",
        "description": "Dhanipur has minor waterlogging only. Main road still passable. Exaggerated reports circulating.",
        "affected_count": 80, "reporter_name": "Sarpanch Dhanipur",
        "is_verified": False, "reliability_score": 55.0, "duplicate_probability": 0.0,
        "contradiction_flag": True,
        "timestamp": t(6.5),
    },
]


DEMO_RESOURCES = [
    {"code": "BOAT-01", "name": "Rescue Boat Alpha", "resource_type": "boat", "capacity": 12,
     "status": "available", "lat": 23.2200, "lng": 85.3100, "base_location": "Nandipura HQ",
     "assigned_village_name": None, "assignment_reason": None},
    {"code": "BOAT-02", "name": "Rescue Boat Beta", "resource_type": "boat", "capacity": 10,
     "status": "deployed", "lat": 23.2050, "lng": 85.3700, "base_location": "Kumarhat Base",
     "assigned_village_name": "Sundarnagar Village", "assignment_reason": "Major flooding – 890 people affected"},
    {"code": "BOAT-03", "name": "Rescue Boat Gamma", "resource_type": "boat", "capacity": 8,
     "status": "available", "lat": 23.1900, "lng": 85.3400, "base_location": "Shivpur Base",
     "assigned_village_name": None, "assignment_reason": None},
    {"code": "AMB-01", "name": "Ambulance Unit 1", "resource_type": "ambulance", "capacity": 4,
     "status": "deployed", "lat": 23.2280, "lng": 85.3510, "base_location": "District Hospital",
     "assigned_village_name": "Rajpur Tola", "assignment_reason": "4 medical emergencies at building collapse site"},
    {"code": "AMB-02", "name": "Ambulance Unit 2", "resource_type": "ambulance", "capacity": 4,
     "status": "available", "lat": 23.2300, "lng": 85.3300, "base_location": "District Hospital",
     "assigned_village_name": None, "assignment_reason": None},
    {"code": "AMB-03", "name": "Ambulance Unit 3", "resource_type": "ambulance", "capacity": 4,
     "status": "available", "lat": 23.2100, "lng": 85.3800, "base_location": "CHC Kumarhat",
     "assigned_village_name": None, "assignment_reason": None},
    {"code": "MED-01", "name": "Medical Team Alpha", "resource_type": "medical_team", "capacity": 8,
     "status": "available", "lat": 23.2200, "lng": 85.3400, "base_location": "District Hospital",
     "assigned_village_name": None, "assignment_reason": None},
    {"code": "MED-02", "name": "Medical Team Beta", "resource_type": "medical_team", "capacity": 6,
     "status": "available", "lat": 23.2000, "lng": 85.3600, "base_location": "CHC Shivpur",
     "assigned_village_name": None, "assignment_reason": None},
    {"code": "EXCAV-01", "name": "Excavator Heavy-01", "resource_type": "excavator", "capacity": 2,
     "status": "deployed", "lat": 23.2510, "lng": 85.3640, "base_location": "PWD Depot",
     "assigned_village_name": "Madhupur", "assignment_reason": "Major structural collapse – debris clearing"},
    {"code": "EXCAV-02", "name": "Excavator Heavy-02", "resource_type": "excavator", "capacity": 2,
     "status": "available", "lat": 23.2100, "lng": 85.3200, "base_location": "PWD Depot",
     "assigned_village_name": None, "assignment_reason": None},
    {"code": "TRUCK-01", "name": "Relief Truck 1", "resource_type": "relief_truck", "capacity": 50,
     "status": "available", "lat": 23.2300, "lng": 85.3500, "base_location": "District HQ",
     "assigned_village_name": None, "assignment_reason": None},
    {"code": "TRUCK-02", "name": "Relief Truck 2", "resource_type": "relief_truck", "capacity": 50,
     "status": "available", "lat": 23.2000, "lng": 85.3700, "base_location": "District HQ",
     "assigned_village_name": None, "assignment_reason": None},
    {"code": "PERS-01", "name": "NDRF Team Alpha", "resource_type": "personnel", "capacity": 20,
     "status": "available", "lat": 23.2250, "lng": 85.3450, "base_location": "NDRF Camp",
     "assigned_village_name": None, "assignment_reason": None},
]


DEMO_ROADS = [
    {"code": "R-01", "name": "NH-23 (National Highway)", "road_type": "highway",
     "from_location": "District HQ", "to_location": "Nandipura Block",
     "from_lat": 23.2200, "from_lng": 85.3100, "to_lat": 23.2350, "to_lng": 85.3200,
     "waypoints": [], "status": "open", "risk_level": "low",
     "distance_km": 8.5, "estimated_time_min": 20, "suitable_for": ["ambulance", "truck", "excavator"],
     "block_reason": None},
    {"code": "R-02", "name": "District Road D-04", "road_type": "district_road",
     "from_location": "Nandipura Block", "to_location": "Sundarnagar Village",
     "from_lat": 23.2350, "from_lng": 85.3200, "to_lat": 23.2080, "to_lng": 85.3870,
     "waypoints": [[23.2200, 85.3500]], "status": "caution", "risk_level": "medium",
     "distance_km": 12.0, "estimated_time_min": 35, "suitable_for": ["ambulance", "truck"],
     "block_reason": "Partial flooding in low sections"},
    {"code": "R-03", "name": "Village Road Kalivadi", "road_type": "village_road",
     "from_location": "Nandipura Block", "to_location": "Kalivadi",
     "from_lat": 23.2350, "from_lng": 85.3200, "to_lat": 23.2150, "to_lng": 85.3340,
     "waypoints": [], "status": "blocked", "risk_level": "critical",
     "distance_km": 4.2, "estimated_time_min": 0, "suitable_for": ["boat"],
     "block_reason": "Road completely washed out by flooding"},
    {"code": "R-04", "name": "Rajpur Access Road", "road_type": "village_road",
     "from_location": "Nandipura Block", "to_location": "Rajpur Tola",
     "from_lat": 23.2350, "from_lng": 85.3200, "to_lat": 23.2280, "to_lng": 85.3510,
     "waypoints": [], "status": "caution", "risk_level": "high",
     "distance_km": 5.8, "estimated_time_min": 25, "suitable_for": ["ambulance", "excavator"],
     "block_reason": "Debris on road – passable with caution"},
    {"code": "R-05", "name": "Dhanipur Road", "road_type": "village_road",
     "from_location": "Nandipura Block", "to_location": "Dhanipur",
     "from_lat": 23.2350, "from_lng": 85.3200, "to_lat": 23.2350, "to_lng": 85.3200,
     "waypoints": [], "status": "flooded", "risk_level": "high",
     "distance_km": 6.1, "estimated_time_min": 0, "suitable_for": ["boat"],
     "block_reason": "Road flooded – 60cm water depth"},
    {"code": "R-06", "name": "Shivpur District Road", "road_type": "district_road",
     "from_location": "District HQ", "to_location": "Shivpur Block",
     "from_lat": 23.2200, "from_lng": 85.3100, "to_lat": 23.1720, "to_lng": 85.3650,
     "waypoints": [], "status": "open", "risk_level": "low",
     "distance_km": 9.5, "estimated_time_min": 22, "suitable_for": ["ambulance", "truck", "excavator"],
     "block_reason": None},
    {"code": "R-07", "name": "Baiganbari Mountain Road", "road_type": "village_road",
     "from_location": "Kumarhat Block", "to_location": "Baiganbari",
     "from_lat": 23.2080, "from_lng": 85.3870, "to_lat": 23.1980, "to_lng": 85.3700,
     "waypoints": [], "status": "blocked", "risk_level": "critical",
     "distance_km": 8.9, "estimated_time_min": 0, "suitable_for": [],
     "block_reason": "Major landslide – complete blockage"},
    {"code": "R-08", "name": "Madhupur Access Road", "road_type": "village_road",
     "from_location": "Nandipura Block", "to_location": "Madhupur",
     "from_lat": 23.2350, "from_lng": 85.3200, "to_lat": 23.2510, "to_lng": 85.3640,
     "waypoints": [], "status": "damaged", "risk_level": "high",
     "distance_km": 7.2, "estimated_time_min": 40, "suitable_for": ["ambulance", "excavator"],
     "block_reason": "Road damaged by seismic activity"},
    {"code": "R-09", "name": "Gopaltola Road", "road_type": "village_road",
     "from_location": "Kumarhat Block", "to_location": "Gopaltola",
     "from_lat": 23.2080, "from_lng": 85.3870, "to_lat": 23.2060, "to_lng": 85.4150,
     "waypoints": [], "status": "caution", "risk_level": "medium",
     "distance_km": 5.5, "estimated_time_min": 28, "suitable_for": ["ambulance", "truck"],
     "block_reason": "Partial flooding – passable with 4WD"},
    {"code": "R-10", "name": "Mahuatoli Road", "road_type": "village_road",
     "from_location": "Shivpur Block", "to_location": "Mahuatoli",
     "from_lat": 23.1720, "from_lng": 85.3650, "to_lat": 23.1850, "to_lng": 85.3480,
     "waypoints": [], "status": "open", "risk_level": "low",
     "distance_km": 3.8, "estimated_time_min": 12, "suitable_for": ["ambulance", "truck", "boat"],
     "block_reason": None},
    {"code": "BRIDGE-01", "name": "Nandipura River Bridge", "road_type": "bridge",
     "from_location": "R-02", "to_location": "Sundarnagar Village",
     "from_lat": 23.2100, "from_lng": 85.3600, "to_lat": 23.2000, "to_lng": 85.3750,
     "waypoints": [], "status": "caution", "risk_level": "high",
     "distance_km": 0.3, "estimated_time_min": 5, "suitable_for": ["ambulance"],
     "block_reason": "Structural assessment ongoing – weight limit reduced"},
    {"code": "BRIDGE-02", "name": "Baiganbari Creek Bridge", "road_type": "bridge",
     "from_location": "R-07", "to_location": "Baiganbari",
     "from_lat": 23.2000, "from_lng": 85.3740, "to_lat": 23.1990, "to_lng": 85.3710,
     "waypoints": [], "status": "damaged", "risk_level": "critical",
     "distance_km": 0.2, "estimated_time_min": 0, "suitable_for": [],
     "block_reason": "Bridge structurally compromised by landslide impact"},
]


DEMO_ALERTS = [
    {
        "alert_type": "critical_zone", "severity": "critical",
        "title": "🔴 Critical Zone: Kalivadi",
        "message": "Kalivadi village has been classified CRITICAL. 980 people at risk. Main road washed out. Rescue boat required immediately.",
        "village_name": "Kalivadi",
    },
    {
        "alert_type": "critical_zone", "severity": "critical",
        "title": "🔴 Critical Zone: Madhupur",
        "message": "Madhupur affected by earthquake + building collapse. 7 medical emergencies. EXCAV-01 dispatched.",
        "village_name": "Madhupur",
    },
    {
        "alert_type": "contradiction", "severity": "warning",
        "title": "⚠️ Contradiction Detected: Kalivadi",
        "message": "Conflicting severity reports for Kalivadi. One report claims complete submersion; another reports minor waterlogging. Satellite evidence supports severe flooding.",
        "village_name": "Kalivadi",
    },
    {
        "alert_type": "contradiction", "severity": "warning",
        "title": "⚠️ Contradiction Detected: Dhanipur",
        "message": "Conflicting access reports for Dhanipur. Sarpanch reports road passable; police reports road blocked. Ground verification recommended.",
        "village_name": "Dhanipur",
    },
    {
        "alert_type": "blackout", "severity": "warning",
        "title": "⚠️ Communication Blackout: Tulsibari",
        "message": "No reports received from Tulsibari for 9 hours. Absence of reports does not indicate safety. Satellite/drone verification recommended.",
        "village_name": "Tulsibari",
    },
    {
        "alert_type": "medical_cluster", "severity": "critical",
        "title": "🚨 Medical Emergency Cluster: Madhupur",
        "message": "7 separate medical emergency reports from Madhupur. Medical team deployment critical.",
        "village_name": "Madhupur",
    },
    {
        "alert_type": "route_blocked", "severity": "warning",
        "title": "🛣️ Critical Route Blocked: R-03 (Kalivadi)",
        "message": "Road R-03 to Kalivadi completely washed out. Only boat access possible.",
        "village_name": "Kalivadi",
    },
    {
        "alert_type": "route_blocked", "severity": "warning",
        "title": "🛣️ Landslide Blockage: R-07 (Baiganbari)",
        "message": "Road R-07 to Baiganbari completely blocked by landslide. Village fully isolated.",
        "village_name": "Baiganbari",
    },
    {
        "alert_type": "satellite_evidence", "severity": "info",
        "title": "📡 Satellite Evidence: Kalivadi",
        "message": "New satellite imagery confirms 72% inundation at Kalivadi. Confidence score updated to 91%.",
        "village_name": "Kalivadi",
    },
    {
        "alert_type": "resource_shortage", "severity": "warning",
        "title": "🚨 Resource Gap: Kalivadi P1 Unassigned",
        "message": "Kalivadi ranked P1 (94/100) but has no rescue resource assigned. Recommend deploying BOAT-01.",
        "village_name": "Kalivadi",
    },
]
